import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:trident/app/ui/theme/colors.dart';

part 'theme.g.dart';

/// The [lightTheme] is a [ThemeData] instance that is generated by Riverpod Generator
@riverpod
ThemeData lightTheme(ref) {
  final color = ColorScheme.fromSeed(
    seedColor: LightAppColors.base,
  );
  return ThemeData(
    colorScheme: color,
  );
}

/// The [darkTheme] is a [ThemeData] instance that is generated by Riverpod Generator
@riverpod
ThemeData darkTheme(ref) {
  final color = ColorScheme.fromSeed(
    seedColor: DarkAppColors.base,
    brightness: Brightness.dark,
  );
  return ThemeData(
    colorScheme: color,
  );
}
