import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:trident/app/core/routes/router.dart';
import 'package:trident/app/ui/theme/theme.dart';

/// The entry point of the application.
class Trident extends ConsumerWidget {
  const Trident({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    /// The [router] is a [GoRouter] instance that is generated by Riverpod Generator
    /// and is used to navigate between pages.
    /// The [light] and [dark] are [ThemeData] instances that are generated by Riverpod Generator
    /// and are dynamically generated if functionality is available
    final router = ref.watch(routerProvider);
    final light = ref.watch(lightThemeProvider);
    final dark = ref.watch(darkThemeProvider);

    return MaterialApp.router(
      theme: light,
      darkTheme: dark,
      debugShowCheckedModeBanner: false,
      routerConfig: router,
    );
  }
}
