import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:trident/app/features/placeholder/presentation/home.dart';

part 'router.g.dart';

/// The [router] is a [GoRouter] instance that is generated by Riverpod Generator
/// Riverpod is used to check auth status
@riverpod
GoRouter router(ref) {
  return GoRouter(
    routes: [
      GoRoute(
        path: '/',
        pageBuilder: (context, state) => const MaterialPage(
          child: PlaceHolderHome(),
        ),
      ),
    ],
  );
}
